import HAMMAM from '@/public/static/desktop/logos/Hammam.png';
import ALAMEER from '@/public/static/desktop/logos/al-ameer.png';
import AL_ARAYES from '@/public/static/desktop/logos/al-arayes_mall.png';
import GLOBAL_DEGREE from '@/public/static/desktop/logos/global_degree.png';
import HIGH_CLASS from '@/public/static/desktop/logos/high_class.png';
import MAHMOUD_EL_BAROUDI from '@/public/static/desktop/logos/mahmoud_el-baroudi.png';
import ROYAL_SCHOOL from '@/public/static/desktop/logos/royal_school.png';
import EISB from '@/public/static/desktop/logos/eisb.png';
import FOURTH_DIM from '@/public/static/desktop/logos/4th.png';
import AL_BODOOR from '@/public/static/desktop/logos/al_bodoor.png';
import BURJ_ALBYAN from '@/public/static/desktop/logos/burj_albyan.png';
import FLY_BAGHDAD from '@/public/static/desktop/logos/fly_baghdad.png';
import LAB from '@/public/static/desktop/logos/lab.png';
import RAJEH_BANK from '@/public/static/desktop/logos/rajeh_bank.png';
export const FIRST = [FLY_BAGHDAD, ROYAL_SCHOOL,HIGH_CLASS, EISB,FOURTH_DIM,BURJ_ALBYAN,RAJEH_BANK,AL_BODOOR,LAB,MAHMOUD_EL_BAROUDI,GLOBAL_DEGREE,AL_ARAYES,ALAMEER,HAMMAM];
